name: Rector

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  schedule:
    # Run weekly on Sundays at 2 AM UTC to catch new Rector rules
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  rector:
    runs-on: ubuntu-latest
    name: Rector Code Quality Check

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch more history for better Git operations
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2
          coverage: none # Disable coverage for performance

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

      - name: Install Rector
        run: composer require rector/rector --dev --with-all-dependencies

      - name: Cache Rector
        uses: actions/cache@v4
        with:
          path: /tmp/rector
          key: rector-${{ hashFiles('rector.php') }}-${{ hashFiles('composer.lock') }}
          restore-keys: rector-

      - name: Run Rector Dry Run
        id: rector-check
        run: |
          vendor/bin/rector process --dry-run --output-format=github
        continue-on-error: true

      - name: Check for Rector changes
        id: rector-changes
        run: |
          if [ ${{ steps.rector-check.outcome }} = "failure" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Rector found code that needs refactoring"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No Rector changes needed"
          fi

      # Only run on push to main/develop branches and if changes are needed
      - name: Run Rector and Auto-fix
        if: |
          steps.rector-changes.outputs.has_changes == 'true' && 
          github.event_name == 'push' && 
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        run: |
          vendor/bin/rector process
          
      - name: Check for modified files
        if: |
          steps.rector-changes.outputs.has_changes == 'true' && 
          github.event_name == 'push' && 
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        id: git-check
        run: |
          if [ -n "$(git diff --name-only)" ]; then
            echo "modified=true" >> $GITHUB_OUTPUT
          else
            echo "modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit Rector changes
        if: |
          steps.rector-changes.outputs.has_changes == 'true' && 
          steps.git-check.outputs.modified == 'true' &&
          github.event_name == 'push' && 
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 Apply Rector refactoring'
          commit_options: '--no-verify'
          file_pattern: '*.php'

      # For PRs, just fail the check if changes are needed
      - name: Fail PR if Rector changes needed
        if: |
          steps.rector-changes.outputs.has_changes == 'true' && 
          github.event_name == 'pull_request'
        run: |
          echo "❌ Rector found code that needs refactoring. Please run 'vendor/bin/rector process' locally and commit the changes."
          exit 1

      - name: Success message
        if: steps.rector-changes.outputs.has_changes == 'false'
        run: |
          echo "✅ Code is already following Rector standards!"

      # Discord notification on failure
      - name: Discord notification on Rector failure
        if: failure() && steps.rector-check.outcome == 'failure'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚨 **Rector Failed** 🚨
            
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            
            **Message:** Rector found code that needs refactoring
            **Action:** Please run `composer rector:fix` locally and commit the changes
            
            **View Details:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      # Discord notification on successful auto-fix
      - name: Discord notification on successful auto-fix
        if: |
          success() && 
          steps.rector-changes.outputs.has_changes == 'true' && 
          steps.git-check.outputs.modified == 'true' &&
          github.event_name == 'push' && 
          (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ✅ **Rector Auto-fix Applied** ✅
            
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Author:** ${{ github.actor }}
            
            **Message:** Rector automatically applied code improvements
            **View Changes:** ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
